name: "Env1 Test Workflow"
on:
  workflow_dispatch:

jobs:
  run_python:
    name: "Python Step"
    uses: ./.github/workflows/template.yaml
    with:
      GHA_ENVIRONMENT: env1
    secrets:
      SECRET: ${{ secrets.SECRET }}
